### ISSUE TITLE
Drag'n'Dropping the window stops Update()

### ISSUE THREAD

**Issue by Insane96** [aiv01/aiv-fast2d#17]
Drag'n'Dropping the window stops Update(), starting again when the window is released.

**Comment by rdeioris** [comment]
Unfortunately this is a limit in the windows api, when you click on a window border the input manager is blocked until you release the button, This happens in unity too with the default settings. Workaround is using a second thread for the game logic, but frankly speaking if my rendering is blocked i prefer my game logic to not go further. Obviously this is not a good approach for networking games, but in such a case the network manager itself could be managed in another thread.
