### ISSUE TITLE
Error 'System.TypeInitializationException'

### ISSUE THREAD

**Issue by alicanheybeli** [aiv01/aiv-fast2d#46]
I copy pasted the example Sprite code,and it gave this error at creating the sprite instance.
'System.TypeInitializationException'

**Comment by unbit** [comment]
Hi, ensure a Window has been created before calling any Fast2D class

**Comment by alicanheybeli** [comment]
it is, here is it

`using System.Threading.Tasks;
using Aiv.Fast2D;
using OpenTK;
namespace WindowsFormsApplication2
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Window mainwindow = new Window("game");
            Sprite sprite = new Sprite(100.0f,100.0f);
            
            // move the sprite
            sprite.position = new Vector2(0, 0);
            //rotate the sprite on the z axis (in degrees)
            sprite.EulerRotation = 90;
            // scale a sprite
            sprite.scale = new Vector2(0.5f, 0.5f);
            while (true) ;
        }
    }
}`

**Comment by unbit** [comment]
which operating system ?

**Comment by alicanheybeli** [comment]
windows 7

**Comment by unbit** [comment]
Maybe it is a pre-opengl 3.3 system, try adding:

```c#
Window.SetObsoleteMode();
```

before instantiating the Window

**Comment by alicanheybeli** [comment]
It works! thanks.
