### ISSUE TITLE
RenderTexture issue with Post Effects

### ISSUE THREAD

**Issue by fdefelici** [aiv01/aiv-fast2d#53]
Don't remember what was the problem. Just write this down as a reminder
Need to ask to @chirone0

**Comment by chirone0** [comment]
[RenderTexture_BUG.zip](https://github.com/aiv01/aiv-fast2d/files/5000700/RenderTexture_BUG.zip)
![RenderTextureBug](https://user-images.githubusercontent.com/16254536/88914025-44231800-d262-11ea-9815-e7356744aea3.png)

**Comment by fdefelici** [comment]
Issue has been fixed applying a workaround and implementing an ad-hoc method. See Mesh.DrawRenderTexture.

The workaround foresees to download Render Texture from the GPU, after the posteffect are applyied and before it will be drawn to the window. Pixels downloaded from the GPU are not affected by any artifacts. 
So this data are loaded in a new texture which will be blit to the window.
By this the rendering is clean.

![immagine](https://user-images.githubusercontent.com/24794993/89043018-29c36a00-d348-11ea-8f5b-0cba6ca52064.png)
